name: Sysdig Secure Scan

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    # required for SARIF upload
    permissions:
      security-events: write
      contents: read
      actions: read

    # scan three Docker-build contexts in parallel
    strategy:
      matrix:
        image:
          - name: vote
            ctx: ./vote
            tag: abtaux/abt-voting-app:vote-${{ github.sha }}
            cat: vote-scan
          - name: worker
            ctx: ./worker
            tag: abtaux/abt-voting-app:worker-${{ github.sha }}
            cat: worker-scan
          - name: result
            ctx: ./result
            tag: abtaux/abt-voting-app:result-${{ github.sha }}
            cat: result-scan

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build ${{ matrix.image.name }}
        run: docker build -t ${{ matrix.image.tag }} ${{ matrix.image.ctx }}

      - name: Sysdig scan ${{ matrix.image.name }}
        id: scan
        uses: sysdiglabs/scan-action@v5
        # let the step “succeed” for GH even if scan fails, so outputs exist
        continue-on-error: true
        with:
          image-tag: ${{ matrix.image.tag }}
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
          stop-on-processing-error: false
          stop-on-failed-policy-eval: false

      - name: Show scanner outputs
        run: |
          echo "sarifReport=${{ steps.scan.outputs.sarifReport }}"
          echo "scanReport=${{ steps.scan.outputs.scanReport }}"

      - name: Upload SARIF ${{ matrix.image.name }}
        if: steps.scan.outputs.sarifReport != ''   # run only if file exists
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.scan.outputs.sarifReport }}
          category: ${{ matrix.image.cat }}

