name: Sysdig Secure Container Scan

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  container-scan:
    runs-on: ubuntu-latest

    permissions:
      security-events: write    # required by upload-sarif
      contents: read
      actions: read

    strategy:
      matrix:
        image:
          - name: vote
            context: ./vote
            tag: abtaux/abt-voting-app:vote
            category: vote-scan
          - name: worker
            context: ./worker
            tag: abtaux/abt-voting-app:worker
            category: worker-scan
          - name: result
            context: ./result
            tag: abtaux/abt-voting-app:result
            category: result-scan

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image ${{ matrix.image.name }}
        run: docker build -t ${{ matrix.image.tag }} ${{ matrix.image.context }}

      - name: Scan image ${{ matrix.image.name }}
        id: sysdig_scan
        uses: sysdiglabs/scan-action@v5
        continue-on-error: true
        with:
          image-tag: ${{ matrix.image.tag }}
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
          sysdig-secure-url: ${{ secrets.SYSDIG_SECURE_URL }}     # optional, default https://secure.sysdig.com
          stop-on-processing-error: false
          stop-on-failed-policy-eval: false

      - name: Debug SARIF path for ${{ matrix.image.name }}
        run: echo "SARIF => ${{ github.workspace }}/sarif.json"

      - name: Upload SARIF (${{ matrix.image.name }})
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/sarif.json
          category: ${{ matrix.image.category }}

