name: Sysdig Secure Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  container-scan:
    runs-on: ubuntu-latest
    permissions:
      # needed for upload-sarif
      security-events: write
      actions: read
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    #-------------------------------------------------
    # VOTE IMAGE
    #-------------------------------------------------
    - name: Build vote image
      run: docker build -t myrepo/vote:latest ./vote

    - name: Scan vote
      id: scan_vote
      uses: sysdiglabs/scan-action@v5
      continue-on-error: true           # let SARIF be produced even if scan “fails”
      with:
        image-tag: myrepo/vote:latest
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}

    - name: Upload SARIF (vote)
      if: always()                      # run even when scan “fails”
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan_vote.outputs.sarifReport }}
        category: vote-scan

    #-------------------------------------------------
    # WORKER IMAGE
    #-------------------------------------------------
    - name: Build worker image
      run: docker build -t myrepo/worker:latest ./worker

    - name: Scan worker
      id: scan_worker
      uses: sysdiglabs/scan-action@v5
      continue-on-error: true
      with:
        image-tag: myrepo/worker:latest
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}

    - name: Upload SARIF (worker)
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan_worker.outputs.sarifReport }}
        category: worker-scan

    #-------------------------------------------------
    # RESULT IMAGE
    #-------------------------------------------------
    - name: Build result image
      run: docker build -t myrepo/result:latest ./result

    - name: Scan result
      id: scan_result
      uses: sysdiglabs/scan-action@v5
      continue-on-error: true
      with:
        image-tag: myrepo/result:latest
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}

    - name: Upload SARIF (result)
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.scan_result.outputs.sarifReport }}
        category: result-scan


