name: Scan Containers

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build vote image
        run: docker build -t myrepo/vote:latest ./vote

      - name: Scan vote image
        id: scan-vote
        uses: sysdiglabs/scan-action@v5
        with:
          image-tag: myrepo/vote:latest
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}

      - name: Upload SARIF for vote
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.scan-vote.outputs.sarifReport }}

      - name: Build worker image
        run: docker build -t myrepo/worker:latest ./worker

      - name: Scan worker image
        id: scan-worker
        uses: sysdiglabs/scan-action@v5
        with:
          image-tag: myrepo/worker:latest
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}

      - name: Upload SARIF for worker
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.scan-worker.outputs.sarifReport }}

      - name: Build result image
        run: docker build -t myrepo/result:latest ./result

      - name: Scan result image
        id: scan-result
        uses: sysdiglabs/scan-action@v5
        with:
          image-tag: myrepo/result:latest
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}

      - name: Upload SARIF for result
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.scan-result.outputs.sarifReport }}
