name: Sysdig Secure Container Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    permissions:
      security-events: write  # required by upload-sarif
      contents: read
      actions: read

    strategy:
      matrix:
        image:
          - name: vote
            build-context: ./vote
            tag: myrepo/vote:latest
            category: vote-scan
          - name: worker
            build-context: ./worker
            tag: myrepo/worker:latest
            category: worker-scan
          - name: result
            build-context: ./result
            tag: myrepo/result:latest
            category: result-scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image ${{ matrix.image.name }}
        run: docker build -t ${{ matrix.image.tag }} ${{ matrix.image.build-context }}

      - name: Scan image ${{ matrix.image.name }}
        id: sysdig_scan
        uses: sysdiglabs/scan-action@v5
        continue-on-error: true
        with:
          image-tag: ${{ matrix.image.tag }}
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
          stop-on-processing-error: false
          stop-on-failed-policy-eval: false

      - name: Debug SARIF path for ${{ matrix.image.name }}
        run: echo "SARIF report => ${{ github.workspace }}/sarif.json"

      - name: Upload SARIF (${{ matrix.image.name }})
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/sarif.json
          category: ${{ matrix.image.category }}
