name: Sysdig Secure Container Scan

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    permissions:
      security-events: write    # required by upload-sarif
      contents: read
      actions: read

    strategy:
      matrix:
        image:
          - name: vote
            ctx: ./vote
            tag: abtaux/abt-voting-app:vote-${{ github.sha }}
            category: vote-scan
          - name: worker
            ctx: ./worker
            tag: abtaux/abt-voting-app:worker-${{ github.sha }}
            category: worker-scan
          - name: result
            ctx: ./result
            tag: abtaux/abt-voting-app:result-${{ github.sha }}
            category: result-scan

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image ${{ matrix.image.name }}
        run: docker build -t ${{ matrix.image.tag }} ${{ matrix.image.ctx }}

      - name: Scan image ${{ matrix.image.name }}
        id: scan
        uses: sysdiglabs/scan-action@v5
        continue-on-error: true
        with:
          image-tag: ${{ matrix.image.tag }}
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
          sysdig-secure-url: ${{ secrets.SYSDIG_SECURE_URL }}
          stop-on-processing-error: false
          stop-on-failed-policy-eval: false

      - name: Show scanner outputs
        run: |
          echo "sarifReport=${{ steps.scan.outputs.sarifReport }}"
          echo "scanReport=${{ steps.scan.outputs.scanReport }}"

      - name: Upload SARIF (${{ matrix.image.name }})
        if: steps.scan.outputs.sarifReport != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.scan.outputs.sarifReport }}
          category: ${{ matrix.image.category }}

