name: Sysdig Secure Container Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  container-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write   # für upload-sarif
      actions: read
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # ------------------------------
    # Scan Vote Image
    # ------------------------------
    - name: Build vote image
      run: docker build -t myrepo/vote:latest ./vote

    - name: Scan vote image
      id: scan_vote
      uses: sysdiglabs/scan-action@v5
      continue-on-error: true
      with:
        image-tag: myrepo/vote:latest
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
        stop-on-processing-error: false     # Scanner läuft bis zum Ende
        stop-on-failed-policy-eval: false   # auch bei Policy‐Verstößen
    - name: Debug Vote SARIF path
      run: echo "Vote SARIF: ${{ github.workspace }}/sarif.json"

    - name: Upload SARIF (vote)
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ github.workspace }}/sarif.json
        category: vote-scan

    # ------------------------------
    # Scan Worker Image
    # ------------------------------
    - name: Build worker image
      run: docker build -t myrepo/worker:latest ./worker

    - name: Scan worker image
      id: scan_worker
      uses: sysdiglabs/scan-action@v5
      continue-on-error: true
      with:
        image-tag: myrepo/worker:latest
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
        stop-on-processing-error: false
        stop-on-failed-policy-eval: false
    - name: Debug Worker SARIF path
      run: echo "Worker SARIF: ${{ github.workspace }}/sarif.json"

    - name: Upload SARIF (worker)
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ github.workspace }}/sarif.json
        category: worker-scan

    # ------------------------------
    # Scan Result Image
    # ------------------------------
    - name: Build result image
      run: docker build -t myrepo/result:latest ./result

    - name: Scan result image
      id: scan_result
      uses: sysdiglabs/scan-action@v5
      continue-on-error: true
      with:
        image-tag: myrepo/result:latest
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
        stop-on-processing-error: false
        stop-on-failed-policy-eval: false
    - name: Debug Result SARIF path
      run: echo "Result SARIF: ${{ github.workspace }}/sarif.json"

    - name: Upload SARIF (result)
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ github.workspace }}/sarif.json
        category: result-scan

